In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")

In [4]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [7]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == "spam" else 0)

In [8]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [10]:
X_train.shape

(4457,)

In [11]:
X_test.shape

(1115,)

In [13]:
type(X_train)

pandas.core.series.Series

In [14]:
X_train[:4]

2825      No need to buy lunch for me.. I eat maggi mee..
1181                           I'm in chennai velachery:)
1785    Dont search love, let love find U. Thats why i...
770     Lol I know! They're so dramatic. Schools alrea...
Name: Message, dtype: object

In [16]:
y_train[:4]

2825    0
1181    0
1785    0
770     0
Name: spam, dtype: int64

In [17]:
type(X_train.values)

numpy.ndarray

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)

In [19]:
X_train_cv

<4457x7770 sparse matrix of type '<class 'numpy.int64'>'
	with 59292 stored elements in Compressed Sparse Row format>

In [22]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [23]:
X_train_cv.shape

(4457, 7770)

In [27]:
v.get_feature_names_out()[4750]
v.get_feature_names_out()

array(['00', '000', '008704050406', ..., 'èn', 'ú1', '〨ud'], dtype=object)

In [25]:
v.vocabulary_

{'no': 4819,
 'need': 4750,
 'to': 6955,
 'buy': 1570,
 'lunch': 4283,
 'for': 2930,
 'me': 4431,
 'eat': 2507,
 'maggi': 4335,
 'mee': 4448,
 'in': 3643,
 'chennai': 1754,
 'velachery': 7292,
 'dont': 2399,
 'search': 5999,
 'love': 4248,
 'let': 4105,
 'find': 2844,
 'thats': 6838,
 'why': 7535,
 'its': 3768,
 'called': 1602,
 'falling': 2756,
 'bcoz': 1247,
 'force': 2931,
 'yourself': 7743,
 'just': 3881,
 'fall': 2754,
 'and': 936,
 'know': 3969,
 'there': 6856,
 'is': 3749,
 'smeone': 6273,
 'hold': 3466,
 'bslvyl': 1526,
 'lol': 4205,
 'they': 6864,
 're': 5618,
 'so': 6306,
 'dramatic': 2434,
 'schools': 5970,
 'already': 896,
 'closed': 1839,
 'tomorrow': 6982,
 'apparently': 993,
 'we': 7445,
 'can': 1620,
 'drive': 2448,
 'the': 6839,
 'inch': 3646,
 'of': 4917,
 'snow': 6301,
 'were': 7490,
 'supposed': 6649,
 'get': 3110,
 'please': 5283,
 'protect': 5497,
 'from': 3014,
 'threats': 6888,
 'sib': 6170,
 'never': 4779,
 'asks': 1074,
 'sensitive': 6048,
 'information': 3677

In [28]:
X_train_np = X_train_cv.toarray()

In [29]:
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [37]:
np.where(X_train_np[0] != 0)

(array([1570, 2507, 2930, 4283, 4335, 4431, 4448, 4750, 4819, 6955]),)

In [32]:
X_train[:4][2825]

'No need to buy lunch for me.. I eat maggi mee..'

In [47]:
X_train_np[0][2507]

1

In [48]:
v.get_feature_names_out()[2507]

'eat'

In [49]:
from sklearn.naive_bayes import MultinomialNB

In [50]:
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [51]:
X_test_cv = v.transform(X_test)

In [52]:
from sklearn.metrics import classification_report

In [53]:
y_pred = model.predict(X_test_cv)

In [54]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       972
           1       0.96      0.92      0.94       143

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [62]:
email = [
    "Hey, can we get together for a movie tomorrow?",
    "Offer ends soon! Hurry before the discount is over! 20% off exclusive offers just for you! Don't miss this reward!"
]

In [63]:
emails_count = v.transform(email)

In [64]:
model.predict(emails_count)

array([0, 1])

In [65]:
from sklearn.pipeline import Pipeline 

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [66]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [68]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       972
           1       0.96      0.92      0.94       143

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

